version: '3'

services: 
  myapp:
    build: .
    volumes: 
    - /usr/src/app
    - /usr/src/app/node_modules
    ports: 
    - 8080:8080
    - 8085:8085
    restart: always
  redis:
    image: redis:alpine
    volumes: 
      - ./data:/data
    entrypoint: redis-server --appendonly yes
    restart: always


